// Generated by Claude.ai
const text = await window.fs.readFile('paste.txt', { encoding: 'utf8' });

// First, extract the date lines and associated album info
const sessions = [];
let currentDate = '';
let lines = text.split('\n');

for (let i = 0; i < lines.length; i++) {
    let line = lines[i].trim();

    // Look for date patterns
    if (/^(Monday|Tuesday|Wednesday|Thursday|Friday|Saturday|Sunday)$/.test(line) &&
        /^Dec \d{1,2}, 2024$/.test(lines[i+1]?.trim())) {
        currentDate = `${line}, ${lines[i+1].trim()}`;
        // Also get the time from the next line that matches time pattern
        let timeIndex = i + 2;
        while (timeIndex < lines.length && !/^\d{1,2}:\d{2} PM$/.test(lines[timeIndex].trim())) {
            timeIndex++;
        }
        if (timeIndex < lines.length) {
            currentDate += ` ${lines[timeIndex].trim()}`;
        }
    }

    // Look for "Hosted By:" which indicates album info follows
    if (line === 'Hosted By:' && currentDate) {
        const artist = lines[i+1]?.trim();
        const album = lines[i+2]?.trim();
        const yearMatch = lines[i+3]?.trim().match(/\((\d{4})\)/);
        const year = yearMatch ? parseInt(yearMatch[1]) : null;

        if (artist && album && year) {
            sessions.push({
                date: currentDate,
                artist: artist,
                album: album,
                year: year
            });
        }
    }
}

// Sort by date/time (which are fortunately in a format that sorts correctly as strings)
sessions.sort((a, b) => a.date.localeCompare(b.date));

console.log(JSON.stringify(sessions, null, 2));